docker:
  import_name: docker
  conda_forge: docker-py

graphviz:
  import_name: graphviz
  conda_forge: python-graphviz

matplotlib:
  import_name: matplotlib
  conda_forge: matplotlib-base

opencv-python:
  import_name: cv2
  conda_forge: opencv

pyqt4:
  import_name: pyqt4
  conda_forge: pyqt
  delimiter_min: "4.0.0"
  delimiter_max: "5.0.0"

pyqt5:
  import_name: pyqt5
  conda_forge: pyqt
  delimiter_min: "5.0.0"
  delimiter_max: "6.0.0"

python-opencv:
  import_name: cv2
  conda_forge: opencv

tables:
  import_name: pytables
  conda_forge: pytables

xxhash:
  import_name: xxhash
  conda_forge: python-xxhash
